name: ummobile
description: App de la Universidad de Montemorelos

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated+by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.3.0+29

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.3
  ummobile_sdk: ^0.0.9
  ummobile_custom_http: ^0.0.3
  fade_shimmer: ^2.0.1
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^1.0.3
  flutter_launcher_icons: ^0.10.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  get: ^4.3.8
  http: ^0.13.5
  dio: ^4.0.6
  intl: ^0.17.0
  oauth2: ^2.0.0
  onesignal_flutter: ^3.2.7
  smooth_page_indicator: ^1.0.0+2
  syncfusion_flutter_calendar: ^20.2.48
  syncfusion_flutter_pdfviewer: ^20.2.48-beta
  syncfusion_localizations: ^20.2.48
  url_launcher: ^6.0.4
  video_player: ^2.1.6
  new_version: ^0.3.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_html: ^2.1.5
  webview_flutter: ^2.8.0
  snippet_coder_utils: ^1.0.13


dev_dependencies:
  flutter_config: ^2.0.0
  flutter_native_splash: ^2.2.0+1
  device_preview: ^1.1.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#6E56C6"
  image: "assets/img/splash.png"
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/img/login_logo.svg
    - assets/img/short_logo.svg
    - assets/img/logo_header.svg
    - assets/img/sitesImg/e42.svg
    - assets/img/sitesImg/conectate.svg
    - assets/img/sitesImg/academico.svg
    - assets/img/sitesImg/UMTV.svg
    - assets/img/no_internet.svg
    - assets/img/no_server.svg
    - assets/img/default-img.jpg
    - assets/translations/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
        
    - family:  MyFlutterApp
      fonts:
       - asset: assets/icons/MyFlutterApp.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
